version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.3-python3.12
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.session

    # These are passed into DockerOperator tasks too (we will pass explicitly in DAG)
    PGHOST: postgres
    PGPORT: "5432"
    PGDATABASE: airflow
    PGUSER: airflow
    PGPASSWORD: airflow

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins

    # IMPORTANT: allow DockerOperator to start sibling containers
    - /var/run/docker.sock:/var/run/docker.sock

  depends_on:
    - postgres

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 20

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  # Build image used by DockerOperator
  traffic-runner:
    build:
      context: .
      dockerfile: Dockerfile.traffic
    image: traffic-runner:latest
    profiles: ["build-only"]

  # API (for AWS/EC2 too)
  traffic-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: airflow
      PGUSER: airflow
      PGPASSWORD: airflow
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  # UI (Streamlit)
  traffic-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      API_BASE_URL: http://traffic-api:8000
    ports:
      - "8501:8501"
    depends_on:
      - traffic-api
